resources:
- name: concourse-release
  type: git
  source:
    uri: https://github.com/xtreme-peter-iskandar/concourse-file-test.git
    branch: master

jobs:
- name: build
  plan:
  - get: concourse-release
  - task: build
    file: concourse-release/module/ci/tasks/build/build.yml
    params:
      CHECKSUM: {{checksum}}
      CHECKSUM_BASE64: {{checksum-b64}}
      BASE64_FILE_DATA: {{base64-file-data}}

